language: python
sudo: false
cache:
  pip: true
python:
  - "3.11"
matrix:
  fast_finish: true
install:
  - pip install uv
  - uv venv
  - uv pip install -e '.[test]'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- firefox -v
script:
  - bin/test
after_success:
  - bin/createcoverage
  - bin/pip install coverage
  - bin/python -m coverage.pickle2json
  - pip install coveralls
  - coveralls
